services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    env_file:
      - open-webui.env
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
    restart: always
    depends_on:
      - litellm
      - tika # Added tika as dependency as it's used in env vars

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

  litellm:
    container_name: litellm
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION_NAME: us-west-2
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@litellm-db:5432/${POSTGRES_DB}
      STORE_MODEL_IN_DB: "True" # allows adding models to proxy via UI
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      UI_USERNAME: ${UI_USERNAME}
      UI_PASSWORD: ${UI_PASSWORD}
    entrypoint: "litellm"
    command:
      - "--config"
      - "/app/config.yml"
      - "--detailed_debug"
    ports:
      - 4000:4000
    volumes:
      - litellm-files:/app
    restart: always
    depends_on:
      - git-checkout
      - litellm-db

  litellm-db:
    container_name: litellm-db
    image: postgres:16-alpine
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./litellm-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  # Service container
  # https://github.com/portainer/portainer/issues/6390#issuecomment-1100954657
  git-checkout:
    container_name: git-checkout
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c "
        if [ -d 'portainer-stacks' ]; then
          cd portainer-stacks && git pull
        else
          git clone https://github.com/abiencourt/portainer-stacks.git
        fi &&
        cp -R ./portainer-stacks/open-webui-litellm/litellm/. /litellm
      "
    volumes:
      - litellm-files:/litellm

volumes:
  open-webui:
  litellm-files:
