litellm_settings:
  drop_params: true

## text and vision
model_list:
  - model_name: bedrock-amazon-nova-lite-v1
    litellm_params:
      model: bedrock/amazon.nova-lite-v1:0
      input_cost_per_token: 0.00000006
      output_cost_per_token: 0.00000024

  ## embedding
  - model_name: bedrock-amazon-titan-embed-text-v2
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v2:0
      input_cost_per_token: 0.00000002

  ## Image Generator
  - model_name: bedrock-sdxl-v1
    litellm_params:
      model: bedrock/stability.stable-diffusion-xl-v1
